CREATE TABLE SCRAPPED(
	id INTEGER PRIMARY KEY NOT NULL,
	id_arret INTEGER NOT NULL,
	id_scrap INTEGER NOT NULL,
	time_saved DATETIME NOT NULL,
	minutes INTEGER NOT NULL,
	theorique  BOOLEAN NOT NULL)
